package com.example.psk_1.mybatis.dao;

import com.example.psk_1.mybatis.model.Course;
import com.example.psk_1.mybatis.model.Lecturer;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface LecturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURER
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURER
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    int insert(Lecturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURER
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    Lecturer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURER
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    List<Lecturer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURER
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    int updateByPrimaryKey(Lecturer record);

    // Manually added methods
    List<Course> selectLecturerCourses(Integer id);
}