package com.example.psk_1.mybatis.dao;

import com.example.psk_1.mybatis.model.Student;
import com.example.psk_1.mybatis.model.StudentCourse;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StudentCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    int insert(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    List<StudentCourse> selectAll();

    // Manually added methods
    void delete(StudentCourse record);
    List<Student> getAllCourseStudents(Integer courseId);
}