package com.example.psk_1.mybatis.model;

import lombok.EqualsAndHashCode;

@EqualsAndHashCode
public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.LECTURER_ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    private Integer lecturerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.ID
     *
     * @return the value of PUBLIC.COURSE.ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.ID
     *
     * @param id the value for PUBLIC.COURSE.ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @return the value of PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @param courseName the value for PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.LECTURER_ID
     *
     * @return the value of PUBLIC.COURSE.LECTURER_ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public Integer getLecturerId() {
        return lecturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.LECTURER_ID
     *
     * @param lecturerId the value for PUBLIC.COURSE.LECTURER_ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public void setLecturerId(Integer lecturerId) {
        this.lecturerId = lecturerId;
    }
}