package com.example.psk_1.mybatis.model;

import lombok.EqualsAndHashCode;

@EqualsAndHashCode
public class Lecturer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LECTURER.ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LECTURER.FIRST_NAME
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LECTURER.LAST_NAME
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    private String lastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LECTURER.ID
     *
     * @return the value of PUBLIC.LECTURER.ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LECTURER.ID
     *
     * @param id the value for PUBLIC.LECTURER.ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LECTURER.FIRST_NAME
     *
     * @return the value of PUBLIC.LECTURER.FIRST_NAME
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LECTURER.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.LECTURER.FIRST_NAME
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LECTURER.LAST_NAME
     *
     * @return the value of PUBLIC.LECTURER.LAST_NAME
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LECTURER.LAST_NAME
     *
     * @param lastName the value for PUBLIC.LECTURER.LAST_NAME
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}