package com.example.psk_1.mybatis.model;

import lombok.EqualsAndHashCode;

@EqualsAndHashCode
public class StudentCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_COURSE.STUDENTLIST_ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    private Integer studentlistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_COURSE.COURSELIST_ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    private Integer courselistId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_COURSE.STUDENTLIST_ID
     *
     * @return the value of PUBLIC.STUDENT_COURSE.STUDENTLIST_ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public Integer getStudentlistId() {
        return studentlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_COURSE.STUDENTLIST_ID
     *
     * @param studentlistId the value for PUBLIC.STUDENT_COURSE.STUDENTLIST_ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public void setStudentlistId(Integer studentlistId) {
        this.studentlistId = studentlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_COURSE.COURSELIST_ID
     *
     * @return the value of PUBLIC.STUDENT_COURSE.COURSELIST_ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public Integer getCourselistId() {
        return courselistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_COURSE.COURSELIST_ID
     *
     * @param courselistId the value for PUBLIC.STUDENT_COURSE.COURSELIST_ID
     *
     * @mbg.generated Fri Apr 25 16:48:11 EEST 2025
     */
    public void setCourselistId(Integer courselistId) {
        this.courselistId = courselistId;
    }
}